### ISSUE TITLE
Adding calendar icon as a prefix for polymer_datepicker

### ISSUE THREAD

**Issue by st-clair-clarke** [dam0vm3nt/polymer_datepicker#6]
Hi Vittorio,
Looking at https://elements.polymer-project.org/elements/paper-input?active=paper-input&view=demo:demo/index.html > Inputs can have prefixes and suffixes, would you please consider placing an calendar icon-prefix or -suffix on the paper-input that will give our user a visual clue as to what the component is for?

Also, allow the developer to change the colour of the icon to suit the theme of the application by attaching properties eg stroke, fill etc for style.

**Comment by dam0vm3nt** [comment]
added possibility to add it at your choice. see the demo.

**Comment by dam0vm3nt** [comment]
I think it's already there. I opted to allow user to specify their own prefix so they can choose everything, from icon to style, for example:

``` html

<date-picker label="as locale"
                     selected-date="{{myDate}}">
            <iron-icon icon="today" style="color:red" suffix></iron-icon>
</date-picker>

```

**Comment by st-clair-clarke** [comment]
Thanks a million for accommodating my suggestion Vittorio.

Cheers

Teddy
